### PR TITLE
Feat/spotlight fixing

### PR DESCRIPTION
**Pull request by Sonzzini**

### CODE REVIEW

**Comment by Sonzzini** [comment]
ACEITEM MINHA PULL REQUEST POR FAVOOOOOOOOOR

**Comment by Sonzzini** [comment]
UNINSTALLING VALORANT
▇▇▇▇▇▇▇▇▇▇▇▇▇▇▢
　　╭━╮╭━╮╭╮　╱ 　　
　　╰━┫╰━┫╰╯╱╭╮ 　　
　　╰━╯╰━╯　╱　╰╯ 　　　　　
　　　     COMPLETE

**Review by andrearteca — COMMENTED** [review]
👍

**Review by andrearteca — APPROVED** [review]
👍👍

**Pull request merged**
